RDKBACCL-1245: Fix BPI OpenWRT build issue
Reason for change: To fix undefined reference to `wpa_sm_get_rsn_override' build issue introduced by rdk-wifi-hal PR#431
Test Procedure: Ensure there are no build issues in latest BPI OpenWRT build
Risks: Medium
Priority: P1

Signed-off-by: Rakhil P E <rakhilpe001@gmail.com>