RDKBACCL-1651 : Observing build issues when we disable generic_mlo (#689)
distro iin BPI RDKB builds
Reason for change: Observed below errors,
../git/src/../platform/banana-pi/platform.c:860:44: error: 'wifi_hal_priv_t' has no member named 'mld_count'
|   860 |     for (unsigned int i = 0; i < g_wifi_hal.mld_count; ++i) {
|       |                                            ^
| ../git/src/../platform/banana-pi/platform.c:861:28: error: 'wifi_hal_priv_t' has no member named 'mld_array'
|   861 |         mld_it = g_wifi_hal.mld_array[i];
|       |                            ^
| ../git/src/../platform/banana-pi/platform.c: In function 'alloc_mld':
| ../git/src/../platform/banana-pi/platform.c:909:39: error: 'wifi_hal_priv_t' has no member named 'mld_array'
|   909 |     new_mld_array = realloc(g_wifi_hal.mld_array,
|       |                                       ^
| ../git/src/../platform/banana-pi/platform.c:910:20: error: 'wifi_hal_priv_t' has no member named 'mld_count'
|   910 |         (g_wifi_hal.mld_count + 1) * sizeof(struct hostapd_mld *));
|       |                    ^
| ../git/src/../platform/banana-pi/platform.c:924:29: error: 'wifi_hal_priv_t' has no member named 'mld_count'
|   924 |     new_mld_array[g_wifi_hal.mld_count] = mld;
|       |                             ^
| ../git/src/../platform/banana-pi/platform.c:926:15: error: 'wifi_hal_priv_t' has no member named 'mld_array'
|   926 |     g_wifi_hal.mld_array = new_mld_array;
|       |               ^
| ../git/src/../platform/banana-pi/platform.c:928:15: error: 'wifi_hal_priv_t' has no member named 'mld_count'
|   928 |     g_wifi_hal.mld_count++;
Test Procedure:  Build successful
Risks: None

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>
(cherry picked from commit d798bd9e97831774c8697e8b8a2f48bd412348ab)