RDKB-61540: cherrypick base MLO work (#660)
* RDKB-61540: Generic MLO support (#332)

* RDKBACCL-668 : Jumping Hostapd 2.11 to 2.12 for wifi 7 MLO (#162)

Reason for change: Adding fetching capabilities for BPI platform
Test Procedure: systemctl status onewifi
Risks: None.

Signed-off-by: ssiras826 <ssiras826@cable.comcast.com>

* RDKBACCL-668 : Jumping Hostapd 2.11 to 2.12 for wifi 7 MLO (#158)

Reason for change: Reverting patches of rdk-wifi-hal wrt to nl core file and API updation with respect to hostapd 2.12
Test Procedure: Command to check core file is ls /tmp/*core* and build got successful
Risks: None.

Signed-off-by: ssiras826 <ssiras826@cable.comcast.com>

* mlo: set common ssid for all vaps (#171)

Signed-off-by: Narendra Varma <narendandu@gmail.com>

* RDKB-61540: generic MLO support

Reason for change: generic MLO support
Test Procedure:
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>

---------

Signed-off-by: ssiras826 <ssiras826@cable.comcast.com>
Signed-off-by: Narendra Varma <narendandu@gmail.com>
Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: SsandhyaR <ssiras826@cable.comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* RDKB-61540: Address MLO compilation issues seen on 2.10 hostap (#348)

Reason for change: Address compilation error for platform using
2.10 or lesser based hostapd to use legacy mechanism for notifying
supplicant event.

Test Procedure: Compilation and build checked.
Risks: Low
Priority: P1

* RDKB-61540: MLO support: fixed link id and ifindex (#357)

Reason for change: fixed link id and ifindex
Test Procedure:
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* RDKB-61540: Fix backhaul station connection (#358)

Reason for change: For station connection in createVAP bring down
of interface is required, address this only for STA mode so as not
to impact MLO connection.
Call the right supplicant event callback to handle supplicant events.

Risks: Low
Priority: P1

Signed-off-by: Amarnath Hullur Subramanyam <amarnath_hullursubramanyam@comcast.com>

* RDKB-61540: Fixed MLO link id lookup (#365)

Reason for change:
 - sometimes API returns wrong link id
 - fixed Pixel client connection by enabling LDPC
Test Procedure:
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* RDKB-61540: Configure MLO links sequentially (#404)

Reason for change:
  Banana Pi R4 driver expects sequential MLO link configuration:
  add link 0, set wiphy 0, start ap 0, add link 1...
Test Procedure:
  Connect MLO client to Banana Pi R4.
  Check internet access.
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>
Co-authored-by: Sathish Kumar Gnanasekaran <gsathish86@gmail.com>

* RDKB-61540: disable HT coexistence (#427)

Reason for change:
  Crash when client connects with 40MHz disabled in HT cap:
  1. Client sends 40 MHz disabled in HT cap

  HT: STA 11:22:33:44:55:66 HT Capabilities Info: 0x402d
  update_sta_ht STA 11:22:33:44:55:66 - no greenfield, num of non-gf stations 1
  update_sta_ht STA 11:22:33:44:55:66 - 20 MHz HT, num of 20MHz HT STAs 1
  HT: Forty MHz Intolerant is set by STA 11:22:33:44:55:66 in Association Request

  2. hostap tries to downgrade bandwith by setting secondary channel

  ht40_intolerant_add
  iface->conf->secondary_channel = 0;

  3. Since other parameters are not updated it later fails in __ieee802_11_set_beacon - hostapd_set_freq_params
  20/40 MHz: center segment 0 (=3) and center freq 1 (=2412) not in sync

  4. Crash on
  params.freq->link_id = -1;

Test Procedure:

  1. Enable 40Mhz bandwidth
  2. Connect Iphone 16
  3. Check hostapd logs

Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* RDKB-61540: fixed double free of MLO STA (#453)

Reason for change:
  MLO STA is freed in HAL by process_frame_mgmt and later by hostapd in
  hostapd_deauth_sta causing use after free crash.
  Free in the HAL does not remove STA from all MLO links. It is removed
  from main link but not from child links. In this case ap_get_sta
  returns STA from child link and hostapd tries to free it again.
  Free in the HAL looks redundant therefore disabled.
Test Procedure:
  Connect-disconnect MLO client. Check no crash.
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* RDKB-61540: Fixed mgt frame registration for MLO (#466)

Reason for change:
   Management frame handler was registered multiple times.
Test Procedure:
   Check no frame handler registration errors in the HAL logs.
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* Feature/rdkb 61540 10 (#463)

* Revert "RDKB-61540: Configure MLO links sequentially (#404)"

This reverts commit bd9920d11887176e477a321cd6c69beb273e2529.

* RDKB-61540: Add nl80211 driver link remove function

This was causing silent failures when deinitializing BSS links or
interfaces. Enable only for Banana Pi as it produces issues on Broadcom
due to MLD handling being done mostly outside of hostap.

* RDKB-61540: fix data-path issue for banana pi

Reason for change:
  Data-path issue due to different configuration flow

Test Procedure:
  Connect MLO client to 2.4G.
  Check ping 10.0.0.1
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>

---------

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Brayan Milczarek <brayan_milczarek@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* Revert "Feature/rdkb 61540 10 (#463)" (#479)

This reverts commit b58c44c6c40d9940ba1f9cc9352a85076ed4d848.

* RDKB-61540: Fix MLO capabilities fetch and rework dump handler (#401)

Reason for change: We were not getting the MLO capabilities from the
netlink subsystem because it requires for the device to use split
dump functionality. BPI lacked added definitions in certain macros.

In the meantime it became evident that the current state of the
wiphy_dump_handler will be hard to maintain not only because of split
dump handling but because of different behaviour for certain devices.

Test Procedure: Check if 3 radios present for non-MLO build and if
device is in operable state(client connections possible, BSS configured
as expected)
Risks: Low
Priority: P1

Signed-off-by: Brayan Milczarek <brayan_milczarek@comcast.com>
Co-authored-by: Sathish Kumar Gnanasekaran <gsathish86@gmail.com>

* RDKB-61540: Fix MLO capabilities fetch and rework dump handler (#487)

Summary: Fix build error with possible value overflow

Signed-off-by: Vitaliy Lyashenko <v.for.vitalik@gmail.com>

* Revert "RDKB-61540: Fixed mgt frame registration for MLO (#466)" (#490)

This reverts commit b064d712c6311162b0bb751a641f666bdc3b7328.

* RDKB-61540 Feature 13 (#500)

* RDKB-61540: Add nl80211 driver link remove function

This was causing silent failures when deinitializing BSS links or
interfaces. Enable only for Banana Pi as it produces issues on Broadcom
due to MLD handling being done mostly outside of hostap.

* RDKB-61540: MLO reconiguration

Reason for change: support of MLO reconfiguration
Test Procedure:
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>

---------

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Brayan Milczarek <brayan_milczarek@comcast.com>

* RDKB-61540 - Feature 15 (#508)

* RDKB-61540: Add link awareness for BPi4

Reason for change: Default helpers were not aware that an interface may
contains same ifidx and different MLO link ids, thus refering to
different interfaces. This was causing the events to be improperly
parsed for Banana PI case, as currently all interfaces with enabled
MLO have ifidx of MLD interface.

Test Procedure: Check if events get delivered, check if channel change
is confirmed
Risks: Low
Priority: P1

Signed-off-by: Brayan Milczarek <brayan_milczarek@comcast.com>

* RDKB-61540: Fix channel switching on BPI-R4

Reason for change: When switching the channels, for MLD AP interface we
need to send NL80211_CMD_CHANNEL_SWITCH on other links in the MLD group
as well.

Test Procedure: Change channel on band, check if change is reflected,
check for information on partner links on other bands
Risks: Low
Priority: P1

Signed-off-by: Brayan Milczarek <brayan_milczarek@comcast.com>

* RDKB-61540: support MLO channel switch

Reason for change:
- Added support of MLO channel switch
- Channel switch has to be done for all links even if channel changed on one band
- When multiple channel changed they are set one by one, therefore need to wait
  for CSA completion on all links before new channel can be set.
- Use proper link ID for CSA events.

Test Procedure:
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>

---------

Signed-off-by: Brayan Milczarek <brayan_milczarek@comcast.com>
Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Brayan Milczarek <brayan_milczarek@comcast.com>

* RDKB-61540: check MLO links completed CSA before channel change (#532)

Reason for change:
  Channel change executed before all links completed CSA breaks
  driver functionality.

Test Procedure:
  - Add MLD and separate interfaces.
  - Change channel on all links:
dmcli eRT setv Device.WiFi.Radio.1.Channel uint 11
dmcli eRT setv Device.WiFi.Radio.2.Channel uint 36
dmcli eRT setv Device.WiFi.Radio.3.Channel uint 5
dmcli eRT setv Device.WiFi.ApplyRadioSettings bool 1

  - Check channel changed.

Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* RDKB-61540: - 19 - Parse MLO STA link RSSI (#527)

Reason for change: parse MLO link RSSI
Test Procedure:
 - Connect client
 - Check associated clients subdoc is sent with RSSI
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* RDKB-61540: ignore stop AP error (#533)

Reason for change: ignore stop AP error since it can be already stopped
Test Procedure:
 - Check VAP configuration is successful
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>

* RDKB-61540: register one frame socket for MLD interface (#539)

Reason for change:
 - Register one frame socket for MLD interface instead of
   per link sockets due to multiple registration errors and
   frame duplications.
 - Socket descriptor check against 0 is not correct since onewifi
   closes stdin and it can be reused by socket() syscall. Use
   data_frames_registered flag instead.
Test Procedure:
  - Check HAL logs for frame socket registration errors.
Risks: Low
Priority: P1

Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* RDKB-61540: Support multiple MLDs (#548)

Reason for change: In case a feature needs more than one MLD. Currently
static configuration is supported - MLD should be added into
InterfaceMap, wifi interfaces precreated and added into appropriate
bridge.
Test Procedure: Verify if MLD devices defined in InterfaceMap.json are
available in the system, check if links are properly configured, verify
client connectivity
Risks: None
Priority: P3

Signed-off-by: Brayan Milczarek <brayan_milczarek@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* RDKB-63680 Port BCAWLAN-282545: OneWifi NetXL association fails in the 3392 OpenBFC 25.2 RDKM (#587)

Signed-off-by: Sushma Natarajan <sushma.natarajan@broadcom.com>
Co-authored-by: Sathish Kumar Gnanasekaran <gsathish86@gmail.com>

* Fix bridge connection for BPi (#607)

Current BananaPi MLO implementation substitues ifidx in existing
interface structures. Because of this substitution, when operating with
interface names we need to make sure that we consider both MLO and
non-MLO scenario and use helpers for task of fetching the current active
interface name.

Signed-off-by: Brayan Milczarek <brayan_milczarek@comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>

* RDKB-61540: To fix build break in sprint branch (#608)

Reason for change: To fix the sprint to build image
Test Procedure: To get images built successfully
Priority: P1
Risks: Low

Signed-off-by: Samyuktha Karthikeyan <samyuktha_karthikeyan@comcast.com>

* RDKBACCL-1336 : Observing compilation errors with latest tip of rdk-wifi-hal (#489)

Reason for change: Re-naming the wifi api's name to avoid the build
errors,
| ../git/src/wifi_hal_nl80211.c:6612:12: error: conflicting types for 'get_nl80211_protocol_features'; have 'u32(int,  u32 *)' {aka 'unsigned int(int,  unsigned int *)'}
|  6612 | static u32 get_nl80211_protocol_features(int nl_id, u32 *feat)
|       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| In file included from ../git/src/wifi_hal_priv.h:86,
|                  from ../git/src/wifi_hal_nl80211.c:43:
| /home/jenkins/jenkinsroot/workspace/BPI-ctrl-dec10/build-bananapi4-rdk-broadband/tmp/work/cortexa53-rdk-linux/rdk-wifi-hal/6.1+gitAUTOINC+0e61c1f919-r0/recipe-sysroot/usr/include/rdk-wifi-libhostap/src/drivers/driver_nl80211.h:451:5: note: previous declaration of 'get_nl80211_protocol_features' with type 'u32(struct wpa_driver_nl80211_data *)' {aka 'unsigned int(struct wpa_driver_nl80211_data *)'}
|   451 | u32 get_nl80211_protocol_features(struct wpa_driver_nl80211_data *drv);
Also, BPI migrated to MP 4.2 release . It have 6.6 kernel and
latest hostap.
Test Procedure: Able to compile rdk-wifi-hal and basic sanity also
passed
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>

---------

Signed-off-by: ssiras826 <ssiras826@cable.comcast.com>
Signed-off-by: Narendra Varma <narendandu@gmail.com>
Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Signed-off-by: Amarnath Hullur Subramanyam <amarnath_hullursubramanyam@comcast.com>
Signed-off-by: Brayan Milczarek <brayan_milczarek@comcast.com>
Signed-off-by: Vitaliy Lyashenko <v.for.vitalik@gmail.com>
Signed-off-by: Sushma Natarajan <sushma.natarajan@broadcom.com>
Signed-off-by: Samyuktha Karthikeyan <samyuktha_karthikeyan@comcast.com>
Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>
Co-authored-by: bogdanbogush2 <bogdan_bogush@comcast.com>
Co-authored-by: SsandhyaR <ssiras826@cable.comcast.com>
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>
Co-authored-by: Amarnath Hullur Subramanyam <amarnath.hs@gmail.com>
Co-authored-by: Sathish Kumar Gnanasekaran <gsathish86@gmail.com>
Co-authored-by: Vitaliy Lyashenko <36844479+vfrvtlk@users.noreply.github.com>
Co-authored-by: bogdanbogush2 <190483419+bogdanbogush2@users.noreply.github.com>
Co-authored-by: sushmanatarajan <sushma.natarajan@broadcom.com>
Co-authored-by: Samyuktha T K <samyuktha_karthikeyan@comcast.com>
Co-authored-by: kpandu987 <37654815+kpandu987@users.noreply.github.com>