REFPLTB-3519 : New rdk-wifi-halif import change is not building (#432)
Reason for change:  Observed below issues in rpi
error: ../platform/raspberry-pi/.libs/librdk_wifihal_la-platform_pi.o: multiple definition of 'wifi_rrm_send_beacon_req'
 .libs/librdk_wifihal_la-wifi_hal_wnm_rrm.o: previous definition here
 error: ../platform/raspberry-pi/.libs/librdk_wifihal_la-platform_pi.o: multiple definition of 'wifi_wnm_send_bss_tm_req'
.libs/librdk_wifihal_la-wifi_hal_wnm_rrm.o: previous definition here
 error: ../platform/raspberry-pi/.libs/librdk_wifihal_la-platform_pi.o: multiple definition of 'handle_wnm_action_frame'
this definitions are already provided in ./wifi_hal_wnm_rrm.c and this
file is added in RPI platform
reference https://github.com/rdkcentral/rdk-wifi-hal/commit/c24ac486aaed208c4deb4df1a040864c0712f487
Test Procedure: rdk-wifi-hal compilation successful
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>
Cherrypicked from commit 833b6789fecb772ae7d7899270a0a1032490c450